DROP TABLE LIKELISTS;
DROP TABLE friendships;
DROP TABLE films;
DROP TABLE association_rating;
DROP TABLE users;
DROP TABLE genre;
DROP TABLE friendship_status;

-- 1. Базовые таблицы без внешних ключей
CREATE TABLE IF NOT EXISTS friendship_status (
    status_id integer PRIMARY KEY,
    status_description varchar(255)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(255)
);

CREATE TABLE IF NOT EXISTS association_rating (
    rating_id varchar(255) PRIMARY KEY,
    rating_description varchar(255)
);

-- 2. Таблицы, от которых зависят другие
CREATE TABLE IF NOT EXISTS users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email varchar(255),
    user_login varchar(255),
    user_name varchar(255),
    user_birthday DATE
);

-- 3. Таблицы с ссылками на предыдущие (создаём ПОСЛЕ association_rating)
CREATE TABLE IF NOT EXISTS films (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(255),
    film_description varchar(255),
    film_releaseDate DATE,
    film_duration INTEGER,
    film_genre_id integer REFERENCES genre(genre_id),
    film_rating_id varchar(255) REFERENCES association_rating(rating_id)
);

-- 4. Таблицы с ссылками на users и другие
CREATE TABLE IF NOT EXISTS friendships (
    user_id integer NOT NULL REFERENCES users(user_id),
    friend_id integer NOT NULL REFERENCES users(user_id),
    status_id integer NOT NULL REFERENCES friendship_status(status_id),
    PRIMARY KEY (user_id, friend_id)
);

-- 5. Последняя таблица с ссылками на films и users
CREATE TABLE IF NOT EXISTS LikeLists (
    film_id integer REFERENCES films(film_id),
    user_id integer REFERENCES users(user_id),
    PRIMARY KEY (film_id, user_id)
);

insert into genre (genre_name) values ('Комедия');
insert into genre (genre_name) values ('Драма');
insert into genre (genre_name) values ('Мультфильм');
insert into genre (genre_name) values ('Триллер');
insert into genre (genre_name) values ('Документальный');
insert into genre (genre_name) values ('Боевик');

insert into association_rating values ('G','у фильма нет возрастных ограничений');
insert into association_rating values ('PG','детям рекомендуется смотреть фильм с родителями');
insert into association_rating values ('PG-13','детям до 13 лет просмотр не желателен');
insert into association_rating values ('R','лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
insert into association_rating values ('NC-17','лицам до 18 лет просмотр запрещён');

insert into friendship_status values (0, 'pending');
insert into friendship_status values (1, 'confirmed');
